# Generated by Django 3.2.4 on 2021-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='Bu juda ajoyib'),
        ),
    ]
