# Generated by Django 3.2.4 on 2021-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=True),
        ),
    ]
